### ISSUE TITLE
Wrong version number: v1.0.3 Published: Feb 21, 2022 .

### ISSUE THREAD

**Issue by masx200** [egregors/TreeNode#6]
Wrong version number: v1.0.3 Published: Feb 21, 2022 .
https://pkg.go.dev/github.com/egregors/TreeNode@v1.0.3

**Comment by egregors** [comment]
@masx200 Ehe... 🤔 Jaaaa, I completely forgot about v1.0.3 version mess. So I tagged this on like [1.0.4](https://pkg.go.dev/github.com/egregors/TreeNode). 
Also, I updated this package for my repo with LeetCode solutions https://github.com/egregors/leetgo/commit/ce375acf1c903ca2bbdc73b75e9e2e0d5b8b5bf7, and everything seems fine so far.

Is it works now for you?

**Comment by masx200** [comment]
thanks you
